services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - prod

  db-test:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - .env.test
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - test

  rabbitmq:
    image: rabbitmq:4-management
    hostname: server
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - prod

  rabbitmq-test:
    image: rabbitmq:4-management
    hostname: server
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.test
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - test

  wallet-migrations:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: >
      sh -c "npm run migrations:run"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    profiles:
      - prod
      - test

  wallet-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
        - DB_HOST=db
        - RABBITMQ_HOST=rabbitmq
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      wallet-migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    profiles:
      - prod

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: node dist/notification.main.js
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      maildev:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - prod


  wallet-service-e2e:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run test:e2e
    env_file:
      - .env.test
    environment:
      - DB_HOST=db-test
      - RABBITMQ_HOST=rabbitmq-test
    depends_on:
      db-test:
        condition: service_healthy
      rabbitmq-test:
        condition: service_healthy
      wallet-migrations:
        condition: service_completed_successfully
    profiles:
      - test

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    profiles:
      - prod

volumes:
  rabbitmq_data: